apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configs.samples.operator.openshift.io
spec:
  group: samples.operator.openshift.io
  names:
    kind: Config
    listKind: ConfigList
    plural: configs
    singular: config
  scope: Cluster
  version: v1
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            architectures:
              description: Architectures determine which hardware architecture(s)
                to install, where x86_64 and ppc64le are the supported choices.
              items:
                type: string
              type: array
            managementState:
              description: ManagementState is top level on/off type of switch for
                all operators. When "Managed", this operator processes config and
                manipulates the samples accordingly. When "Unmanaged", this operator
                ignores any updates to the resources it watches. When "Removed", it
                reacts that same wasy as it does if the Config object is deleted,
                meaning any ImageStreams or Templates it manages (i.e. it honors the
                skipped lists) and the registry secret are deleted, along with the
                ConfigMap in the operator's namespace that represents the last config
                used to manipulate the samples,
              type: string
            samplesRegistry:
              description: SamplesRegistry allows for the specification of which registry
                is accessed by the ImageStreams for their image content.  Defaults
                on the content in https://github.com/openshift/library that are pulled
                into this github repository, but based on our pulling only ocp content
                it typically defaults to registry.redhat.io.
              type: string
            skippedImagestreams:
              description: SkippedImagestreams specifies names of image streams that
                should NOT be created/updated.  Admins can use this to allow them
                to delete content they don’t want.  They will still have to manually
                delete the content but the operator will not recreate(or update) anything
                listed here.
              items:
                type: string
              type: array
            skippedTemplates:
              description: SkippedTemplates specifies names of templates that should
                NOT be created/updated.  Admins can use this to allow them to delete
                content they don’t want.  They will still have to manually delete
                the content but the operator will not recreate(or update) anything
                listed here.
              items:
                type: string
              type: array
          type: object
        status:
          properties:
            architectures:
              description: Architectures determine which hardware architecture(s)
                to install, where x86_64 and ppc64le are the supported choices.
              items:
                type: string
              type: array
            conditions:
              description: Conditions represents the available maintenance status
                of the sample imagestreams and templates.
              items:
                properties:
                  lastTransitionTime:
                    description: The last time the condition transitioned from one
                      status to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: The last time this condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of condition.
                    type: string
                type: object
              type: array
            managementState:
              description: operatorv1.ManagementState reflects the current operational
                status of the on/off switch for the operator.  This operator compares
                the ManagementState as part of determining that we are turning the
                operator back on (i.e. "Managed") when it was previously "Unmanaged".
              type: string
            samplesRegistry:
              description: SamplesRegistry allows for the specification of which registry
                is accessed by the ImageStreams for their image content.  Defaults
                on the content in https://github.com/openshift/library that are pulled
                into this github repository, but based on our pulling only ocp content
                it typically defaults to registry.redhat.io.
              type: string
            skippedImagestreams:
              description: SkippedImagestreams specifies names of image streams that
                should NOT be created/updated.  Admins can use this to allow them
                to delete content they don’t want.  They will still have to manually
                delete the content but the operator will not recreate(or update) anything
                listed here.
              items:
                type: string
              type: array
            skippedTemplates:
              description: SkippedTemplates specifies names of templates that should
                NOT be created/updated.  Admins can use this to allow them to delete
                content they don’t want.  They will still have to manually delete
                the content but the operator will not recreate(or update) anything
                listed here.
              items:
                type: string
              type: array
            version:
              description: Version is the value of the operator's payload based version
                indicator when it was last successfully processed
              type: string
          type: object
