apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coreos-pull-secret-reader
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-samples-operator-kube-system-secret-reader
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: cluster-samples-operator
  namespace: openshift-cluster-samples-operator
roleRef:
  kind: Role
  name: coreos-pull-secret-reader
  apiGroup: rbac.authorization.k8s.io
