kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-samples-operator-kube-system-edit
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: cluster-samples-operator
  namespace: openshift-cluster-samples-operator
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
